[[items]]
pattern = "top_down_rainbow"
seconds = 10
options = { color_map_name = "twilight" }

[[items]]
pattern = "spider"
seconds = 10
options = { color_map_name = "plasma" }

[[items]]
pattern = "snake"
seconds = 60

[[items]]
pattern = "faces_linear"
seconds = 60

[[items]]
pattern = "scandown"
seconds = 10
options = { secondsPerCycle = 5, bandWidth = 1}

[[items]]
pattern = "scandown"
seconds = 10
options = { secondsPerCycle = 2, bandWidth = 0.5}

[[items]]
pattern = "scandown"
seconds = 10
options = { secondsPerCycle = 1, bandWidth = 0.25}

[[items]]
pattern = "scandown"
seconds = 10
options = { secondsPerCycle = 0.5, bandWidth = 0.1}

[[items]]
pattern = "address-test-2"
seconds = 5

[[items]]
pattern = "helix"
seconds = 5
options = { mode = 1, whiteOnly = true, saturationSpeed = 0, decay = 0.95 }

[[items]]
pattern = "tunnel"
seconds = 60

[[items]]
pattern = "helix"
seconds = 60
options = { mode = 0, whiteOnly = false, saturationSpeed = 1, decay = 0.90 }

[[items]]
pattern = "gpt3"
seconds = 60

[[items]]
pattern = "img_2d_projection"
seconds = 100

[[items]]
pattern = "faces_random"
seconds = 60


[[items]]
pattern = "helix"
seconds = 60
options = { mode = 1, whiteOnly = false, saturationSpeed = 0, decay = 0.98 }

[[items]]
pattern = "rainbow-spot"
seconds = 40

[[items]]
pattern = "matrix-rain"
seconds = 30

[[items]]
pattern = "faces_seq"
seconds = 60








